name: MSBuild

on: [ push, pull_request ]

jobs:

  build_windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 3
      matrix:
        build_configuration: [ Release ]
        build_platform: [ x64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Show MSBuild version
        run: msbuild -version

      - name: Run MSBuild
        run: msbuild RebootAt.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

      - name: Archive artifacts for x64
        if: matrix.build_platform == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: rebootat_x64
          path: ${{ matrix.build_platform }}/${{ matrix.build_configuration }}/RebootAt.exe
